//
//  MCURegisterSVD.swift
//  CallMate
//
//  Loads SVD-derived register names and bit fields from SF32LB52x_registers.json (generated by scripts/svd_to_registers_json.py).
//

import Foundation

/// One bit field in a register (name + position/size).
struct SVDField: Equatable {
    let name: String
    let bitOffset: Int
    let bitWidth: Int

    /// Extract field value from a 32-bit register value.
    func value(from regValue: UInt32) -> UInt32 {
        let mask = bitWidth >= 32 ? UInt32.max : (UInt32(1) << bitWidth) - 1
        return (regValue >> bitOffset) & mask
    }
}

/// Register metadata from SVD: name + fields.
struct SVDRegisterMetadata: Equatable {
    let name: String
    let fields: [SVDField]
}

/// Lookup table: (peripheral name, byte offset) -> register metadata.
final class SVDRegistry {
    static let shared = SVDRegistry()

    /// Key: peripheral name, Value: array of (addressOffset in bytes, metadata)
    private var byPeripheral: [String: [(addressOffset: Int, meta: SVDRegisterMetadata)]] = [:]

    private init() {
        loadFromBundle()
    }

    private func loadFromBundle() {
        guard let url = Bundle.main.url(forResource: "SF32LB52x_registers", withExtension: "json"),
              let data = try? Data(contentsOf: url),
              let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
              let periphs = json["peripherals"] as? [[String: Any]] else {
            return
        }
        for p in periphs {
            guard let name = p["name"] as? String,
                  let regs = p["registers"] as? [[String: Any]] else { continue }
            var list: [(Int, SVDRegisterMetadata)] = []
            for r in regs {
                guard let offset = r["addressOffset"] as? Int,
                      let regName = r["name"] as? String else { continue }
                var fields: [SVDField] = []
                if let arr = r["fields"] as? [[String: Any]] {
                    for f in arr {
                        guard let fn = f["name"] as? String,
                              let bo = f["bitOffset"] as? Int,
                              let bw = f["bitWidth"] as? Int else { continue }
                        fields.append(SVDField(name: fn, bitOffset: bo, bitWidth: bw))
                    }
                }
                list.append((offset, SVDRegisterMetadata(name: regName, fields: fields)))
            }
            list.sort { $0.0 < $1.0 }
            byPeripheral[name] = list
        }
    }

    /// Look up register metadata by peripheral name and byte offset (0, 4, 8, ...).
    func metadata(peripheralName: String, byteOffset: Int) -> SVDRegisterMetadata? {
        guard let list = byPeripheral[peripheralName] else { return nil }
        return list.first { $0.addressOffset == byteOffset }?.meta
    }

    /// Check if any SVD data was loaded (so we can show names).
    var isLoaded: Bool { !byPeripheral.isEmpty }
}
